apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-mlapp
spec:
  selector:
    matchLabels:
      app: test-mlapp
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: test-mlapp
    spec:
      containers:
      - name: test-mlapp
        image: ${REPOSITORY_TAG}
        resources:
          requests:
             memory: 200Mi
             cpu: 0.5

        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: test-mlapp

spec:
  
  selector:
    app: test-mlapp

  ports:
    - name: http
      port: 80
 

  type: ClusterIP
